services:
  php:
    build:
      context: ./docker
      dockerfile: php-apache.Dockerfile
    ports:
      - ${APP_PORT:-8080}:80
    volumes:
      - ./src:/var/www/html
    environment:
      PHP_XDEBUG_MODE: debug,develop
      PHP_XDEBUG_AUTOSTART: yes
      PHP_XDEBUG_HOST: host.docker.internal
      PHP_XDEBUG_PORT: 9003
      PHP_XDEBUG_IDE_KEY: phpstorm
      PHP_IDE_CONFIG: serverName=${PROJECT_NAME}
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0-debian
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_FORWARD_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql_data:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
